[package]
name = "sqlite"
version = "1.0.0"
description = "SQLite database library"
edition = "2024"
entry = "src/lib.knull"
authors = ["Knull Team"]
license = "MIT"
repository = "https://github.com/4fqr/knull"

[dependencies]
